first small changes
SpikeInterface/spikeextractors pull request #566
Opened 2021-02-10 13:38 UTC by luiztauffer

- [x] have the `pyopenephys.File()` available as an attribute, so NWB data interfaces might have access to some fields that are not necessarily relevant to to the RecordingExtractor
- [x] get traces in int16 or float (uV)
- [ ] set channel gains

2021-02-13 14:17 UTC, alejoe91 requested changes

2021-02-13 14:17 UTC, alejoe91 commented on spikeextractors/extractors/openephysextractors/openephysextractors.py
> +    def __init__(self, folder_path, *, experiment_id=0, recording_id=0, dtype='int16'):
Hi @luiztauffer 

I'd keep `float` as default, but add a `dtype` arg to the `get_traces` to allow for dynamically select the dtype.

Note that these changes will be soon superseeded by the `return_scaled` arg.

2021-02-13 14:17 UTC, alejoe91 commented on spikeextractors/extractors/openephysextractors/openephysextractors.py
>                     self._recording.analog_signals[0].gain
```
def get_traces(self, channel_ids=None, start_frame=None, end_frame=None, dtype=None):
        if dtype is not None:
             assert dtype in ["int16", "float"], "'dtype' can be 'int16' or 'float'"
        else:
             dtype = self._dtype
        if dtype == 'int16':   # Returns traces as int16
            return self._recording.analog_signals[0].signal[channel_ids, start_frame:end_frame]
        elif dtype == 'float':   # Returns traces as uV
            return self._recording.analog_signals[0].signal[channel_ids, start_frame:end_frame] * \
                   self._recording.analog_signals[0].gain
```

2021-02-15 16:02 UTC, luiztauffer commented
@alejoe91 it seems like there's no use for `dtype` on `__init__()`, I think we could just remove it from there.
I can replace already the logic on `get_traces` to accept return_scaled arg instead of dtype.
what do you think?

2021-02-16 08:29 UTC, alejoe91 commented
@luiztauffer the `dtype`/`return_scaled` changes are already there in the `return_scaled` branch. (https://github.com/SpikeInterface/spikeextractors/blob/return_scaled/spikeextractors/extractors/openephysextractors/openephysextractors.py#L39-L45) 
 
I guess that the only change would be then to expose the `fileobj`. Is it ok if I point this PR to the `return_scaled` branch and we merge there?

2021-02-16 13:25 UTC, luiztauffer commented
@alejoe91 sure, we can merge it there! But there are other changes beside fileobj, for instance the if condition is inverted in this code you shared, and gain handling there does not work
but I think they will be solved if we merge these branch there

2021-02-18 11:37 UTC, alejoe91 commented
@luiztauffer do we still need this after merging https://github.com/SpikeInterface/spikeextractors/pull/572?

2021-02-18 12:13 UTC, luiztauffer commented
@alejoe91 no, its the same branch, Im closing it

2021-02-18 12:13 UTC, closed without merging